---
title: "População por municípios"
format: html
editor: visual
---

Download dos dados em:

-   Prévia da População dos Municípios com base nos dados do Censo Demográfico 2022 coletados até 25/12/2022: <https://www.ibge.gov.br/estatisticas/sociais/populacao/22827-censo-demografico-2022.html?edicao=35938>

-   Dados do censo de 2010: <https://www.ibge.gov.br/estatisticas/sociais/populacao/9662-censo-demografico-2010.html?edicao=10503&t=resultados>

## Dependências

Carregando pacotes necessários:

```{r}
#| warning: false
#| message: false
library(tidyverse)
library(readxl)
library(janitor)
```

Carregando os municípios de interesse:

```{r}
source("R/municipios_interesse.R")
```

## Leitura e limpeza dos dados

```{r}
dados <-
  read_xls("dados/POP2022_Municipios_20230622.xls", skip = 1) |>
  filter(UF == "SP") |>
  janitor::clean_names() |>
  filter(
    nome_do_municipio %in% c(
      muni_prioritarios_para_tarcisio,
      muni_intermediarios,
      muni_sedes_regionais_sabesp
    )
  ) |>
 rename(name_muni = nome_do_municipio, populacao_estimada_2022 = populacao) |>
  mutate(populacao_estimada_2022 = readr::parse_number(populacao_estimada_2022)) 

head(dados) |> 
  knitr::kable()

dados |> 
 writexl::write_xlsx("output/tabela_amauri_pop_2022.xlsx")
```

## Dados Censo 2010

```{r}
#| warning: false
#| message: false
dados_2010_censo <- read_xls("dados/censo_2010-Tabela 4.20.1.1.xls", skip = 4) |> 
  janitor::clean_names() |> 
  drop_na(x1) |>
  select(name_muni = x1, populacao_2010 = total) |> 
  tibble::rowid_to_column() |> 
  mutate(inicio_muni = stringr::str_starts(name_muni, "Municípios e Distritos|Municípios e Bairros"),
        marcador = cumsum(inicio_muni)) |> 
  filter(marcador == 1) |> 
  select(name_muni, populacao_2010) |> 
  distinct() |> 
  group_by(name_muni) |> 
  summarise(populacao_2010 = max(populacao_2010))

head(dados_2010_censo) |> 
  knitr::kable()
```

## Comparação entre 2010 e 2022

```{r}
dados_comparacao <- dados |> 
  left_join(dados_2010_censo) |> 
  select(name_muni, populacao_2010, populacao_estimada_2022) |> 
  mutate(
    porc_crescimento = round(((populacao_estimada_2022 - populacao_2010) / populacao_2010) * 100,2)
  ) |> 
  select(name_muni, populacao_2010, populacao_estimada_2022, porc_crescimento) 

dados_comparacao |> 
 writexl::write_xlsx("output/tabela_amauri_pop_comparacao.xlsx")

head(dados_comparacao) |> 
  knitr::kable()

```
